spring:
  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      globalcors:
        cors-configurations:
          '[/**]': # 모든 경로에 적용
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: hub-service
          uri: lb://hub-service
          predicates:
            - Path=/v1/hubs/**
          filters:
            - "RewritePath=/v1/hubs(?:/(?<path>.*))?, /\\${path}"

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/v1/products/**
          filters:
            - "RewritePath=/v1/products(?:/(?<path>.*))?, /\\${path}"

        - id: company-service
          uri: lb://company-service
          predicates:
            - Path=/v1/companies/**
          filters:
            - "RewritePath=/v1/companies(?:/(?<path>.*))?, /\\${path}"

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/v1/orders/**
          filters:
            - 'RewritePath=/v1/orders(?:/(?<path>.*))?, /${path}'

        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/v1/deliveries/**
          filters:
            - 'RewritePath=/v1/deliveries(?:/(?<path>.*))?, /${path}'

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/v1/notifications/**
          filters:
            - "RewritePath=/v1/notifications(?:/(?<path>.*))?, /\\${path}"

        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=/v1/ai/**
          filters:
            - "RewritePath=/v1/ai(?:/(?<path>.*))?, /\\${path}"

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/v1/users/**
          filters:
            - "RewritePath=/v1/users(?:/(?<path>.*))?, /\\${path}"

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /api-docs.html
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: list
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /user-service/v3/api-docs
        name: USER API
      - url: /hub-service/v3/api-docs
        name: HUB API
      - url: /order-service/v3/api-docs
        name: ORDER API
      - url: /company-service/v3/api-docs
        name: COMPANY API
      - url: /product-service/v3/api-docs
        name: PRODUCT API
      - url: /delivery-service/v3/api-docs
        name: DELIVERY API
      - url: /ai-service/v3/api-docs
        name: AI API
      - url: /notification-service/v3/api-docs
        name: NOTIFICATION API
