keycloak:
  server-url: https://keycloak.code-factory.co.kr
  realm: smartlogis
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  admin-username: ${KEYCLOAK_ADMIN_USERNAME}
  admin-password: ${KEYCLOAK_ADMIN_PASSWORD}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace